import { MapPin, Sun, Sunset, Moon, House } from 'lucide-react';
const days = [
{date:'05',day:'Monday',title:'Touch down in Tokyo.',area:'Seoul → Tokyo',morning:'Keep it open',afternoon:'Arrive at Airbnb',evening:'Shinjuku',notes:'Stay up until 10 p.m.–midnight.'},
{date:'06',day:'Tuesday',title:'A little style. A little jazz.',area:'Harajuku → Shinjuku',morning:'Keep it open',afternoon:'Harajuku / Omotesando',evening:'Shinjuku PIT Inn Jazz',notes:'Doors 19:00 · Starts 19:30. Tickets on the day: ¥4,400 + tax, including one drink. Afterward: Omoide Yokocho & Golden Gai.'},
{date:'07',day:'Wednesday',title:'Old Tokyo meets the unexpected.',area:'Asakusa → Akihabara',morning:'Sensoji',afternoon:'Akihabara',evening:'Asakusa Sumo Club',notes:'¥16,000 · 18:00 or 20:30.',link:'https://asakusa-sumo.com/reserve/'},
{date:'08',day:'Thursday',title:'Deep cuts & bright lights.',area:'Nakano → Shibuya',morning:'Keep it open',afternoon:'Nakano Broadway',evening:'Shibuya'},
{date:'09',day:'Friday',title:'Good taste, all day.',area:'Tsukiji → Ginza',morning:'Keep it open',afternoon:'Tsukiji Fish Market',evening:'Ginza / Nihombashi',notes:'Omakase in Ginza: ¥18,150 (tax included) · 12 dishes · 2–8 people · 120 minutes.'},
{date:'10',day:'Saturday',title:'Big game. Last big night.',area:'Tokyo → Roppongi',morning:'Keep it open',afternoon:'Tokyo Giants · NPB Climax Series',evening:'Roppongi'},
{date:'11',day:'Sunday',title:'One for the books.',area:'Tokyo → USA',morning:'Keep it open',afternoon:'Airport',evening:'Heading home'}];
export default function Home(){return <main id="top">
<section className="hero wrap"><img src="https://images.unsplash.com/photo-1607094751416-13c531c1caac?auto=format&fit=crop&w=2000&q=85" alt="Neon signs illuminating a Shinjuku street in Tokyo at night" width="2000" height="1125" fetchPriority="high"/><div className="shade"/><div className="hero-content"><h1>Japan Bachelor Trip</h1><div className="trip-meta"><span>October 5–11, 2026</span><span><MapPin size={16}/> Tokyo, Japan</span></div></div></section>
<section className="itinerary wrap" id="itinerary"><div className="section-heading"><div><h2>Itinerary<span>.</span></h2></div><div className="stay"><House size={18}/><div><span>HOME BASE</span><p>Tokyo Airbnb</p></div></div></div>
{days.map((d,i)=><article className="day" id={'oct-'+d.date} key={d.date}><div className="date"><span>OCT</span><strong>{d.date}</strong><span>{d.day}</span></div><div className="day-content"><div className="day-heading"><h3>{d.title}</h3><span className="location"><MapPin size={13}/>{d.area}</span></div><div className="schedule"><div><p className="period"><Sun size={15}/> MORNING</p><p className={d.morning==='Keep it open'?'muted':''}>{d.morning}</p></div><div><p className="period"><Sunset size={15}/> AFTERNOON</p><p>{d.afternoon}</p></div><div><p className="period"><Moon size={15}/> EVENING</p><p>{d.evening}</p></div></div>{d.notes&&<div className="notes"><span>THE DETAILS</span><p>{d.notes} {d.link&&<a href={d.link} target="_blank" rel="noreferrer">Reservations ↗</a>}</p></div>}</div><span className="day-no">DAY 0{i+1}</span></article>)}
<p className="plan-note">The plan, with room for a few good detours. Times and prices are from the trip itinerary; bookings are not confirmed here.</p></section>
<footer className="footer wrap"><span className="brand"><b className="dot"/> MADE FOR THE MEMORIES.</span><a href="https://unsplash.com/photos/R_dy2QWsQmE" target="_blank" rel="noreferrer">Tokyo photo by Nicolas Lindsay ↗</a><a href="#top">Back to top ↑</a></footer></main>}


